server:
  port: 8088

spring:
  application:
    name: "tian_blog"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 986132
    url: jdbc:mysql:///tblog?useSSL=true&characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.tian.tblog.bean
  mapper-locations: classpath*:com/tian/tblog/mapper/*.xml